const mongoose = require('mongoose');

// create schema
const postSchema = mongoose.Schema(
	{
		postId: {
			type: mongoose.Schema.Types.ObjectId,
		},
		title: {
			type: String,
		},
		content: String,
		location: String,
		// userId have not implement
		// get user id generated by mongodb
		username: String,
		geo: {
			lat: { type: Number },
			lng: { type: Number },
		},
		photos: {
			type: Number,
		},
		date: Date,
	},
	{
		timestamps: true,
	}
);

const Post = mongoose.model('Post', postSchema);

module.exports = Post;

/*
postId: '', // use mongodb default __id
cityId: '',
userId: '',
title: '',
content: '',
photos: [],
likes: 0,
create_date: '',
*/
